### PR TITLE
Adding auto-generated CircleCI 2.0 config file

### PR DESCRIPTION
**Pull request by mxplusb**

### CODE REVIEW

**Comment by bengerman13** [comment]
did circle not work without those spaces? the new version is actually improper yaml (that many lenient parsers accept anyway), and the old version is correct yaml.

**Comment by bengerman13** [comment]
> did circle not work without those spaces? the new version is actually improper yaml (that many lenient parsers accept anyway), and the old version is correct yaml.

I was wrong - this is valid yaml, but the original was also valid yaml, and the two versions are equivalent.

**Comment by mxplusb** [comment]
I also think they are equivalent, I was in the process of troubleshooting Circle when Circle told me I needed to follow these steps: https://circleci.com/sunset1-0/.

I do agree they are semantically equivalent. Do we want to dump this?

**Comment by bengerman13** [comment]
I think we should go ahead. I'll stop grumbling about the non-indented sequence format now that I know it's valid. It's what we're using everywhere else, so we might as well be consistent about it.

**Pull request merged**
